/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
export type PutApiV1UsersMeBody = {
  date_of_birth?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  password?: string | null;
  password_confirmation?: string | null;
  profile_picture?: string | null;
};

export type PutApiV1SightingsIdBody = {
  description?: string | null;
  flower_id?: number | null;
  latitude?: number | null;
  longitude?: number | null;
  name?: string | null;
};

export type PostApiV1SightingsBody = {
  description?: string;
  flower_id?: number;
  latitude?: number;
  longitude?: number;
  name?: string;
  picture?: Blob;
};

export type GetApiV1SightingsParams = {
  page?: number;
};

export type GetApiV1SightingsSightingIdLikesParams = {
  page?: number;
};

export type PostApiV1SightingsSightingIdCommentsBody = {
  content?: string;
};

export type GetApiV1SightingsSightingIdCommentsParams = {
  page?: number;
};

export type PostApiV1UsersLoginBody = {
  email?: string;
  password?: string;
};

export type PostApiV1UsersRegisterBody = {
  date_of_birth?: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  password?: string;
};

export type GetApiV1FlowersSearchParams = {
  query: string;
};

export type GetApiV1FlowersRandomParams = {
  page?: number;
};

export type PostApiV1FlowersBody = {
  description?: string;
  features?: string;
  latin_name?: string;
  name?: string;
  profile_picture?: Blob;
};

export type GetApiV1FlowersParams = {
  page?: number;
};

export type GetApiV1FlowersFavoritesParams = {
  page?: number;
};

export interface Comment {
  content?: string;
  id?: number;
  sighting_id?: number;
  user_full_name?: string;
  user_id?: number;
}

export interface Like {
  id?: number;
  sighting_id?: number;
  user_full_name?: string;
  user_id?: number;
}

export interface Favorite {
  flower?: Flower;
  id?: number;
  user_id?: number;
}

export interface Sighting {
  description?: string | null;
  flower_id?: number | null;
  id?: number;
  latitude?: number | null;
  longitude?: number | null;
  name?: string | null;
}

export type UserUser = {
  first_name?: string;
  id?: number;
  last_name?: string;
};

export interface User {
  user?: UserUser;
}

export interface Flower {
  favorite?: boolean;
  id?: number;
  latin_name?: string;
  name?: string;
  profile_picture?: string;
  sightings?: number;
}

export interface Pagination {
  current_page?: number;
  next_page?: number;
  prev_page?: number;
  total_pages?: number;
}

export interface CommentList {
  comments?: Comment[];
  meta?: Pagination;
}

export interface LikeList {
  likes?: Like[];
  meta?: Pagination;
}

export interface FavoriteList {
  meta?: Pagination;
  sightings?: Favorite[];
}

export interface SightingList {
  meta?: Pagination;
  sightings?: Sighting[];
}

export interface FlowerList {
  flowers?: Flower[];
  meta?: Pagination;
}

export interface AuthToken {
  auth_token?: string;
}

export interface AuthTokenError {
  auth_token?: string | null;
  error?: string;
}
